
const ERR_USER_NOT_FOUND = "ERR_USERNAME_NOT_FOUND";
const ERR_PASSWORD_MISMATCH = "ERR_PASSWORD_MISMATCH";


const errors = {
    ERR_USER_NOT_FOUND,
    ERR_PASSWORD_MISMATCH
}

export default errors;
